### ISSUE TITLE
Swiss incompatibility with split VMCs

### ISSUE THREAD

**Issue by tatehaga** [bodgit/memcardpro#26]
Swiss as it stands expects a Game ID with the revision number appended to the end.  For example when loading Mario Power Tennis, the VMC is created as GOME0101 for revision 1.1 as opposed to GOME0100 for revision 1.0 or GOME01 as memcardpro utility currently produces.  Can be fixed by manually appending a revision number however this currently breaks out of the box compatibility with this tool and the Memcard pro GC.

**Comment by tatehaga** [comment]
Oops, found the flag...

**Comment by bodgit** [comment]
I thought the Memcard Pro GC firmware was going to be updated so it also looked for files without those extra bytes. I'll check mine and see what does or doesn't work with the latest firmware.
