### ISSUE TITLE
Make sure MemCardPro GC is compatible with the upcoming Game Cube FlippyDrive

### ISSUE THREAD

**Issue by genestrashcan** [bodgit/memcardpro#35]
Make sure the MemCardPro GC is compatible with the upcoming Game Cube FlippyDrive when it's released.

The flippy drive is a upcoming solder free optical drive emulator for the game cube that can be installed and also preserves the original optical drive.

https://flippydrive.com/

**Comment by bodgit** [comment]
This repository isn't for the MemCardPro firmware, this is just a utility to work with it.

You probably want to email 8bitmods (https://8bitmods.com/), although I'm sure they're aware of the FlippyDrive. They also have a Discord server where you can chat to the developers directly.
